sudo: true
language: php
php:
  - '7'
services:
  - mysql
#mysql:
#  database: activecollab_insight_test
#  username: root
#  encoding: utf8mb4
install: composer install --dev
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'create database if not exists activecollab_insight_test;'
script: phpunit -c test/phpunit.xml
